name:                fees-polysemy
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- servant
- servant-server
- aeson
- generic-aeson
- wai
- warp
- polysemy-plugin
- polysemy

default-extensions:
- OverloadedStrings
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-packages
  - -fplugin=Polysemy.Plugin

library:
  source-dirs: src

executables:
  fees-polysemy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fees-polysemy

tests:
  fees-polysemy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fees-polysemy
    - hspec
    - hspec-discover
    - QuickCheck
    - hspec-wai

verbatim:
  cabal-version: 3.0
